services:
  db:
    image: postgres:14-alpine
    container_name: perfume_db
    restart: always
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=perfumedb
    volumes:
      - ./database:/docker-entrypoint-initdb.d
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d perfumedb"]
      interval: 10s
      timeout: 5s
      retries: 5
  backend:
    build: ./backend
    container_name: perfume_backend
    restart: always
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "5000:5000"
    env_file:
      - ./backend/.env
  frontend:
    build: ./frontend
    container_name: perfume_frontend
    restart: always
    ports:
      - "80:80"
    depends_on:
      - backend
volumes:
  postgres_data:
